### ISSUE TITLE
Branch Naming Rules

### ISSUE THREAD

**Issue by enfycius** [psgstellar/Stellar#7]
* Branch 명명 규칙 정하기

**Comment by hoartist** [comment]
branch 명명규칙을 이전과 같이 하되, 추가 사항으로써 (feature/#1-구현하고자 하는 기능의 제목) 으로 하고자 햇으면 합니다.

**Comment by enfycius** [comment]
> branch 명명규칙을 이전과 같이 하되, 추가 사항으로써 (feature/#1-구현하고자 하는 기능의 제목) 으로 하고자 햇으면 합니다.

좋습니다 !
